version: '3.1'

services:

  hackerads:
    build: .
    container_name: hackerads

    environment:
      DB_HOST: mysql-db
      DB_USER: user
      DB_PASSWORD: test-password
      DB_NAME: hackerads

    command: ["sh", "-c", "sleep 2 && python main.py"]  # Sleeping 2 seconds to give time for mysql instance to start
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_DATABASE: hackerads
      MYSQL_PASSWORD: test-password
      MYSQL_ROOT_PASSWORD: root-test-password

    volumes:
      - db_data:/var/lib/mysql

    ports:
      - 3306:3306

volumes:
  db_data:

networks:
  hackerads:
